# Travis-CI Build for sltbench
# see travis-ci.org for details

sudo: required

dist: precise

language: cpp

# magic dance to include only compilers with c++11 support
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CXX_COMPILER=g++-4.9 C_COMPILER=gcc-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CXX_COMPILER=g++-5 C_COMPILER=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: CXX_COMPILER=clang++-3.6 C_COMPILER=clang-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: CXX_COMPILER=clang++-3.7 C_COMPILER=clang-3.7

script:
  - mkdir build && pushd build && cmake -DBUILD_TESTS=ON -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && popd
  - cmake --build ./build
  - build/sltbench_unittests

