# Travis-CI Build for sltbench
# see travis-ci.org for details

dist: xenial

language: cpp

matrix:
  include:

    - os: linux
      compiler: clang       

    - os: linux
      compiler: gcc

    - os: osx

script:
  - mkdir build && pushd build && cmake -DSLT_BUILD_TESTS=ON -DSLT_BUILD_EXAMPLES=ON -DSLT_BUILD_HISTOGRAMMER=ON -DSLT_BUILD_AUTOLEARNING=ON .. && popd
  - cmake --build ./build --parallel
  - build/tests/sltbench_unittests
