version: '{build}'

configuration:
  - Debug
  - Release

environment:
  matrix:
    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015"

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015 Win64"

matrix:
  fast_finish: true

build_script:
  - git submodule update --init --recursive
  - md build -Force
  - cd build
  - cmake "-DSLT_BUILD_TESTS=ON" "-DSLT_BUILD_EXAMPLES=ON" "-DSLT_BUILD_HISTOGRAMMER=ON" "-DSLT_BUILD_AUTOLEARNING=ON" "-DCMAKE_BUILD_TYPE=%configuration%" ..
  - cmake --build . --config %configuration%
  - cd ..

test_script:
  - cd build\tests\%configuration%
  - sltbench_unittests.exe

artifacts:
  - path: 'build/CMakeFiles/*.log'
    name: logs
